### ISSUE TITLE
To'g'ri yozish

### ISSUE THREAD

**Issue by abdulatifkhan** [UmarAbdurazzoq/alishertour#1]
So'zlarni bir tilda yozishimiz kerak, shunda chalg'ish kamroq bo'ladi!😊

![screen](https://user-images.githubusercontent.com/68887519/98633877-2165cc80-2344-11eb-8e98-83979280eb4b.jpg)

**Comment by UmarAbdurazzoq** [comment]
to'g'irlaymiz :)

**Comment by UmarAbdurazzoq** [comment]
fixed this issue
