### ISSUE TITLE
Htmlda to'ldirilishi. mumkin bo'lgan kodlar

### ISSUE THREAD

**Issue by ozbeg** [UmarAbdurazzoq/alishertour#2]
<img width="613" alt="Screen Shot 2020-11-10 at 10 59 55" src="https://user-images.githubusercontent.com/68459737/98633858-1d39af00-2344-11eb-9c91-893204aad61a.png">
dastur o'zbek tilidabo'lgani uchun lang = "uz " yozganingiz yaxshiroq
Titleda document o'rniga dastur nomini yozib qo'yish kerak menimcha :))

**Comment by UmarAbdurazzoq** [comment]
fixed this issues
